import { defineConfig, devices } from '@playwright/test';

const lineUserId = 'mock-guide-customer';

export default defineConfig({
  testDir: './e2e',
  testMatch: /guide-screenshots\.spec\.ts/,
  fullyParallel: false,
  workers: 1,
  retries: 0,
  timeout: 180_000,
  expect: { timeout: 15_000 },
  reporter: [['list']],
  use: {
    baseURL: 'http://127.0.0.1:5174',
    locale: 'ja-JP',
    viewport: { width: 1440, height: 1000 },
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [{ name: 'guide-chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: [
    {
      command: 'node apps/api/dist/server.js',
      url: 'http://127.0.0.1:4100/health',
      reuseExistingServer: false,
      timeout: 120_000,
      env: {
        ...process.env,
        NODE_ENV: 'development',
        API_HOST: '127.0.0.1',
        API_PORT: '4100',
        CORS_ORIGIN: 'http://127.0.0.1:5174',
        WEB_ORIGIN: 'http://127.0.0.1:5174',
        JWT_SECRET: 'guide-only-jwt-secret-not-for-production',
        LINE_MESSAGING_CHANNEL_ACCESS_TOKEN: '',
        LINE_MESSAGING_CHANNEL_SECRET: '',
        LINE_CHANNEL_ACCESS_TOKEN: '',
        LINE_CHANNEL_SECRET: '',
        LINE_LOGIN_LIFF_ID: '',
        LINE_LIFF_ID: '',
        LINE_ID_TOKEN_VERIFICATION_MODE: 'mock',
        LINE_ID_TOKEN_MOCK_VALUE: 'mock-liff-id-token',
        LINE_ID_TOKEN_MOCK_USER_ID: lineUserId,
        LINE_ID_TOKEN_MOCK_DISPLAY_NAME: 'LINEデモ顧客',
        LINE_NOTIFICATION_WORKER_INTERVAL_MS: '500',
        EMAIL_TRANSPORT: 'mock',
        EMAIL_FROM_ADDRESS: 'no-reply@guide.invalid',
        EMAIL_TOKEN_ENCRYPTION_KEY: 'local-guide-only-encryption-key-2026',
        EMAIL_MOCK_OUTPUT_DIR: '/tmp/line-queue-guide-email',
        PAYMENT_MODE: 'demo',
        MEDIA_STORAGE_MODE: 'mock',
      },
    },
    {
      command: 'npm run dev -w apps/web -- --host 127.0.0.1 --port 5174 --strictPort',
      url: 'http://127.0.0.1:5174',
      reuseExistingServer: false,
      timeout: 120_000,
      env: {
        ...process.env,
        VITE_API_URL: 'http://127.0.0.1:4100',
        VITE_LIFF_ID: '',
        VITE_LIFF_MOCK: 'true',
        VITE_LIFF_MOCK_LOGGED_IN: 'true',
        VITE_LIFF_MOCK_FRIEND: 'true',
        VITE_LIFF_MOCK_USER_ID: lineUserId,
        VITE_LIFF_MOCK_DISPLAY_NAME: 'LINEデモ顧客',
        VITE_LIFF_MOCK_INIT_DELAY_MS: '0',
        VITE_LIFF_DEFAULT_BOOKING_PATH: '/liff/qr/demo-queue-lab-2026',
        VITE_PAYMENT_MODE: 'demo',
        VITE_GOOGLE_MAPS_API_KEY: '',
        VITE_GOOGLE_MAPS_MAP_ID: '',
      },
    },
  ],
});
